env:
    BUILD_HOST: Kernel-CI
    BUILD_USER: AzurE
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Kernel-CI"
  trigger_type: manual
  timeout_in: 120m
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  env_script:
      - cat /etc/os*
      - env

  sync_script:
      curl -sL https://raw.githubusercontent.com/AzurE-007/CI_kernel_xiaomi_raphael/main/sync.sh | bash

  build_script:
      curl -sL https://raw.githubusercontent.com/AzurE-007/CI_kernel_xiaomi_raphael/main/build.sh | bash